blank_issues_enabled: false
contact_links:
  - name: GDG Algiers Community server 
    url: https://discord.gg/7EvsP7eemQ
    about: Our discord server 
  - name: GDG Algiers Website
    url: https://www.gdgalgiers.com/
    about: Our website